type User {
  id: Int!
  email: String!
  username:String!
  password: String!
  name: String
}

input UserInput{
  email: String!
  name: String
  username:String!
  password: String!
}

type Query{
  users: [User!]!
  user(id: Int!): User!
}

type Mutation {
  createUser(data: UserInput!): User!
  updateUser(id: Int, data: UserInput!): User! 
  deleteUser(id: Int!): Boolean
}

type Subscription{
  userAdded: User!
}